export const dataWC = 
{"APIResults":
  {"APICallResult":"0","APICallDiagnostic":"OK","OpCodesProcessed":"1","OpCodesInError":"0" , 
  "OpCodeResults":[
    {"OpCode":"EEL","Status":"0","Message":"OK", "Results":[ 
      {
        "EventKey": 715996,
        "Description": "'  NEW - 20. EBB - LIVE - ENGLISH",
        "EventCode": "",
        "Abstract": "<strong>Employee Business Briefing - English</strong><br>\n<br><br>\n",
        "EventType": "STUDIO",
        "RuntimeDuration": "",
        "EarlyEntranceMinutes": 30,
        "EventGrouping": "EBB Template Layouts",
        "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/Thumbnail_placeholder_2019.png",
        "RequiresRegistration": 0,
        "Active": 0,
        "LaunchNewWindow": 1,
        "IsOnDemand": 0,
        "NewWindowWidth": 0,
        "NewWindowHeight": 0,
        "BoothKey": 0,
        "BoothTitle": "",
        "CustomSortOrder": 0,
        "ExitAction": 7,
        "ExitData": "https://",
        "ExitActionTarget": "_self",
        "SubjectCategory": 0,
        "Category": 0,
        "CreatedOnDate": "2023-07-24 12:51:01.880",
        "OnDemandEventKey": 0,
        "EventSpeakerKey": 0,
        "MaxConcurrentViewers": 0,
        "Keywords": "",
        "LocaleID": 0,
        "ParamBlock": "^^^^^^^^14106",
        "FromDateTime": "",
        "ToDateTime": "",
        "SecondScreen": 0,
        "OnDemandFromDateTime": "",
        "OnDemandToDateTime": ""
    }, {
        "EventKey": 710671,
        "Description": "'  Promote Attendee to Presenter Demo",
        "EventCode": "",
        "Abstract": "<strong>Event Title</strong><br /><br />\nOriginating from Location, Room<br /> \nCity, State<br />\nMonth Day, Year<br /><br />",
        "EventType": "STUDIO",
        "RuntimeDuration": "",
        "EarlyEntranceMinutes": 30,
        "EventGrouping": "Webcasts",
        "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/Thumbnail_placeholder_2019.png",
        "RequiresRegistration": 0,
        "Active": 0,
        "LaunchNewWindow": 1,
        "IsOnDemand": 0,
        "NewWindowWidth": 0,
        "NewWindowHeight": 0,
        "BoothKey": 333222,
        "BoothTitle": "                 Hidden Events",
        "CustomSortOrder": 0,
        "ExitAction": 0,
        "ExitData": "380826",
        "ExitActionTarget": "_self",
        "SubjectCategory": 0,
        "Category": 0,
        "CreatedOnDate": "2023-05-31 16:13:25.050",
        "OnDemandEventKey": 0,
        "EventSpeakerKey": 0,
        "MaxConcurrentViewers": 0,
        "Keywords": "",
        "LocaleID": 0,
        "ParamBlock": "",
        "FromDateTime": "",
        "ToDateTime": "",
        "SecondScreen": 0,
        "OnDemandFromDateTime": "",
        "OnDemandToDateTime": ""
    }, {
        "EventKey": 734250,
        "Description": "'  Responsive Test / DEMO",
        "EventCode": "",
        "Abstract": "<p><strong>Event Title</strong><br /><br /> \nOriginating from Location, Room<br /> \nCity, State<br /> \nMonth Day, Year<br /><br /></p>",
        "EventType": "STUDIO",
        "RuntimeDuration": "",
        "EarlyEntranceMinutes": 30,
        "EventGrouping": "Webcasts",
        "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/Thumbnail_placeholder_2019.png",
        "RequiresRegistration": 0,
        "Active": 0,
        "LaunchNewWindow": 1,
        "IsOnDemand": 0,
        "NewWindowWidth": 0,
        "NewWindowHeight": 0,
        "BoothKey": 333222,
        "BoothTitle": "                 Hidden Events",
        "CustomSortOrder": 0,
        "ExitAction": 0,
        "ExitData": "363346",
        "ExitActionTarget": "_self",
        "SubjectCategory": 0,
        "Category": 0,
        "CreatedOnDate": "2024-02-08 09:34:24.530",
        "OnDemandEventKey": 0,
        "EventSpeakerKey": 0,
        "MaxConcurrentViewers": 0,
        "Keywords": "",
        "LocaleID": 0,
        "ParamBlock": "",
        "FromDateTime": "",
        "ToDateTime": "",
        "SecondScreen": 0,
        "OnDemandFromDateTime": "",
        "OnDemandToDateTime": ""
    },{
        "EventKey": 705633,
        "Description": " 2Q GSMG & GWES Town Hall in Ireland - May 16, 2023",
        "EventCode": "",
        "Abstract": "<strong>2Q GSMG & GWES Town Hall in Ireland </strong><br /><br />\nMay 16, 2023<br /><br />\n",
        "EventType": "STUDIO",
        "RuntimeDuration": "",
        "EarlyEntranceMinutes": 30,
        "EventGrouping": "Webcasts",
        "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/05_16_2Q.png",
        "RequiresRegistration": 0,
        "Active": 0,
        "LaunchNewWindow": 1,
        "IsOnDemand": 0,
        "NewWindowWidth": 0,
        "NewWindowHeight": 0,
        "BoothKey": 271503,
        "BoothTitle": "                                               Global Services",
        "CustomSortOrder": 0,
        "ExitAction": 0,
        "ExitData": "372204",
        "ExitActionTarget": "_self",
        "SubjectCategory": 0,
        "Category": 0,
        "CreatedOnDate": "2023-04-17 10:36:35.360",
        "OnDemandEventKey": 0,
        "EventSpeakerKey": 0,
        "MaxConcurrentViewers": 0,
        "Keywords": "",
        "LocaleID": 0,
        "ParamBlock": "",
        "FromDateTime": "",
        "ToDateTime": "",
        "SecondScreen": 0,
        "OnDemandFromDateTime": "",
        "OnDemandToDateTime": ""
    }, 
    {
      "EventKey": 645303,
      "Description": "HR Exchange - English - May 5, 2022",
      "EventCode": "",
      "Abstract": "<strong>HR Exchange </strong><br>\nMay 5, 2022<br><br>\n",
      "EventType": "STUDIO",
      "RuntimeDuration": "",
      "EarlyEntranceMinutes": 30,
      "EventGrouping": "Webcasts",
      "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/05_05_HR_Exchange.png",
      "RequiresRegistration": 0,
      "Active": 1,
      "LaunchNewWindow": 1,
      "IsOnDemand": 1,
      "NewWindowWidth": 0,
      "NewWindowHeight": 0,
      "BoothKey": 271501,
      "BoothTitle": "                                         Human Resources",
      "CustomSortOrder": 0,
      "ExitAction": 3,
      "ExitData": "308515",
      "ExitActionTarget": "_self",
      "SubjectCategory": 0,
      "Category": 0,
      "CreatedOnDate": "2022-02-03 15:28:30.320",
      "OnDemandEventKey": 0,
      "EventSpeakerKey": 0,
      "MaxConcurrentViewers": 0,
      "Keywords": "",
      "LocaleID": 0,
      "ParamBlock": "",
      "FromDateTime": "",
      "ToDateTime": "",
      "SecondScreen": 0,
      "OnDemandFromDateTime": "",
      "OnDemandToDateTime": ""
  }, {
      "EventKey": 601406,
      "Description": "HR Exchange - English - November 3, 2021 ",
      "EventCode": "",
      "Abstract": "<p><strong>HR Exchange </strong><br /> November 3, 2021 <br /><br /><br /></p>",
      "EventType": "STUDIO",
      "RuntimeDuration": "",
      "EarlyEntranceMinutes": 30,
      "EventGrouping": "Webcasts",
      "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/11_03_HR.png",
      "RequiresRegistration": 0,
      "Active": 1,
      "LaunchNewWindow": 1,
      "IsOnDemand": 1,
      "NewWindowWidth": 0,
      "NewWindowHeight": 0,
      "BoothKey": 271501,
      "BoothTitle": "                                         Human Resources",
      "CustomSortOrder": 0,
      "ExitAction": 3,
      "ExitData": "281183",
      "ExitActionTarget": "_self",
      "SubjectCategory": 0,
      "Category": 0,
      "CreatedOnDate": "2021-09-01 08:29:47.057",
      "OnDemandEventKey": 0,
      "EventSpeakerKey": 0,
      "MaxConcurrentViewers": 0,
      "Keywords": "",
      "LocaleID": 0,
      "ParamBlock": "",
      "FromDateTime": "",
      "ToDateTime": "",
      "SecondScreen": 0,
      "OnDemandFromDateTime": "",
      "OnDemandToDateTime": ""
  }, {
      "EventKey": 346341,
      "Description": "HR Exchange - English - November 6, 2019",
      "EventCode": "",
      "Abstract": "<p><strong>HR Exchange</strong></p>\n<p>Presented live from Kenilworth, NJ</p>\n<p>November 6, 2019</p>\n",
      "EventType": "STUDIO",
      "RuntimeDuration": "",
      "EarlyEntranceMinutes": 30,
      "EventGrouping": "Webcasts",
      "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/11_06_HR_EXCHANGE.png",
      "RequiresRegistration": 0,
      "Active": 0,
      "LaunchNewWindow": 1,
      "IsOnDemand": 1,
      "NewWindowWidth": 0,
      "NewWindowHeight": 0,
      "BoothKey": 271501,
      "BoothTitle": "                                         Human Resources",
      "CustomSortOrder": 0,
      "ExitAction": 3,
      "ExitData": "137416",
      "ExitActionTarget": "_self",
      "SubjectCategory": 0,
      "Category": 0,
      "CreatedOnDate": "2019-10-10 23:36:17.753",
      "OnDemandEventKey": 0,
      "EventSpeakerKey": 0,
      "MaxConcurrentViewers": 0,
      "Keywords": "",
      "LocaleID": 0,
      "ParamBlock": "",
      "FromDateTime": "",
      "ToDateTime": "",
      "SecondScreen": 0,
      "OnDemandFromDateTime": "",
      "OnDemandToDateTime": ""
  }, {
      "EventKey": 301145,
      "Description": "HR Exchange - English - October 4, 2018",
      "EventCode": "",
      "Abstract": "<p><strong>HR Exchange</strong></p>\n<p>Presented live from Rahway, NJ</p>\n<p>October 4, 2018</p>\n",
      "EventType": "STUDIO",
      "RuntimeDuration": "",
      "EarlyEntranceMinutes": 30,
      "EventGrouping": "Webcasts",
      "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/10_04_HR.png",
      "RequiresRegistration": 0,
      "Active": 0,
      "LaunchNewWindow": 1,
      "IsOnDemand": 1,
      "NewWindowWidth": 0,
      "NewWindowHeight": 0,
      "BoothKey": 271501,
      "BoothTitle": "                                         Human Resources",
      "CustomSortOrder": 0,
      "ExitAction": 0,
      "ExitData": "109699",
      "ExitActionTarget": "_self",
      "SubjectCategory": 0,
      "Category": 0,
      "CreatedOnDate": "2018-08-23 09:15:10.580",
      "OnDemandEventKey": 0,
      "EventSpeakerKey": 0,
      "MaxConcurrentViewers": 0,
      "Keywords": "",
      "LocaleID": 0,
      "ParamBlock": "",
      "FromDateTime": "",
      "ToDateTime": "",
      "SecondScreen": 0,
      "OnDemandFromDateTime": "",
      "OnDemandToDateTime": ""
  }, {
      "EventKey": 351948,
      "Description": "HR Exchange - February 6, 2020",
      "EventCode": "",
      "Abstract": "<p><strong>HR Exchange</strong></p>\n<p>Presented live from Kenilworth, NJ</p>\n<p>February 6, 2020</p>\n",
      "EventType": "STUDIO",
      "RuntimeDuration": "",
      "EarlyEntranceMinutes": 30,
      "EventGrouping": "Webcasts",
      "IconImage": "https://files.onlinexperiences.com/FileLibrary/2836/4/02_06_HR_EX.png",
      "RequiresRegistration": 0,
      "Active": 0,
      "LaunchNewWindow": 1,
      "IsOnDemand": 1,
      "NewWindowWidth": 0,
      "NewWindowHeight": 0,
      "BoothKey": 271501,
      "BoothTitle": "                                         Human Resources",
      "CustomSortOrder": 0,
      "ExitAction": 7,
      "ExitData": "https://research.zarca.com/r/Kp5HGX",
      "ExitActionTarget": "_self",
      "SubjectCategory": 0,
      "Category": 0,
      "CreatedOnDate": "2019-12-09 13:15:09.047",
      "OnDemandEventKey": 0,
      "EventSpeakerKey": 0,
      "MaxConcurrentViewers": 0,
      "Keywords": "",
      "LocaleID": 0,
      "ParamBlock": "",
      "FromDateTime": "",
      "ToDateTime": "",
      "SecondScreen": 0,
      "OnDemandFromDateTime": "",
      "OnDemandToDateTime": ""
  }
]}]}};
